---
# tasks file for base

- name: Install NTP daemon
  sudo: true
  yum: name=ntp state=installed

- name: NTP autostart
  sudo: true
  service: name=ntpd enabled=yes

- name: Copy ntp.conf
  sudo: true
  template: src=ntp.conf.j2 dest=/etc/ntp.conf
  notify: restart ntp

- name: Create Ansible service account
  sudo: true
  user: name=ansible comment="ansible service account" group=wheel

- name: Distribute ansible user public key
  sudo true
  authorized_key: user=ansible key="{{ lookup('file', '/home/ansible/ansible.pub') }}
