---
# tasks file for base

- name: Install NTP daemon
  sudo: true
  yum: name=ntp state=installed

- name: NTP autostart
  sudo: true
  service: name=ntpd enabled=yes

- name: Configure NTP
  sudo: true
  template: src=ntp.conf.j2 dest=/etc/ntp.conf
  notify: Restart NTP daemon